### PR TITLE
Add Lean action in CI

### PR DESCRIPTION
**Pull request by zhassan-aws**
Add Lean action in CI to make sure the package doesn't break.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by zhassan-aws** [comment]
This is an example run in my fork: https://github.com/zhassan-aws/rust-lean-models/actions/runs/10584292641/job/29328218478

**Comment by tautschnig** [comment]
Does the action have some issues? It seems it is trying to save the cache twice (and the second one fails).

**Review by tautschnig — APPROVED** [review]
Approving modulo the concerns with the action itself.

**Comment by zhassan-aws** [comment]
Good catch. I'm seeing this error in other repos that use the action though, e.g:

https://github.com/leanprover-community/aesop/actions/runs/10507096078/job/29108109514#step:5:4

Not sure what the error means.

**Comment by tautschnig** [comment]
> Good catch. I'm seeing this error in other repos that use the action though, e.g:

Yes, this doesn't seem to be an issue with how you use it. It just makes me wonder about the quality of the action itself. Might just need some engaging with the action to help them improve it.

**Comment by zhassan-aws** [comment]
Created https://github.com/leanprover/lean-action/issues/96 to ask about the error.

**Pull request merged**
